config/routes.rb
Rails.application.routes.draw do


  #devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do

      resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :reservation_items, only: [:new, :create, :edit, :update, :destroy]
      end

    end # v1
  end # api

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reservation_items, only: [:new, :create, :edit, :update]
  end

  root to: "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/reservation_item.rb
class ReservationItem < ApplicationRecord
  belongs_to :reservation

  before_create :chosenItem
  before_update :compareReturnQtyToBorrowedQty
  after_update_commit :checkReservationStatus


  def chosenItem
    item_id = self.requested_item
    self.requested_item = Item.find(item_id).name
    self.item_id = item_id
  end

  def compareReturnQtyToBorrowedQty

    # Dirty callbacks - Checks if user edited the return field
    if quantity_returned_changed?

      # Check if qty return = qty borrowed
      if self.quantity_returned == self.quantity_borrowed
        self.returned_flag = true   # Complete return, close case
        return true
      end

      # Check if qty return < qty borrowed
      if self.quantity_returned < self.quantity_borrowed
        self.returned_flag = false
        return true
      end

      if self.quantity_returned > self.quantity_borrowed
          return false
          #self.errors.add(:quantity_returned, "is invalid") if self.quantity_returned > self.quantity_borrowed
          flash[:error] = "Cannot return more than what was borrowed"
      end
      
    end
  end


  # Updates reservation's completed flag if borrower have returned all items
  def checkReservationStatus

    completed_count = 0

    reservation = Reservation.find(self.reservation_id)

    reservation.reservation_items.each do |ri|
        if ri.returned_flag == true
          completed_count += 1
        end
    end

    if completed_count == 0
      reservation.completed_flag = false
      reservation.save

    elsif completed_count != reservation.reservation_items.count
        reservation.completed_flag = false
        reservation.save

    elsif completed_count == reservation.reservation_items.count
        reservation.completed_flag = true
        reservation.save
    end
  end

end

app/controllers/api/v1/reservation_items_controller.rb
module Api
  module V1
    class ReservationItemsController < ApplicationController
      protect_from_forgery with: :null_session

      def create

        reservation = Reservation.find(params[:reservation_id])
        reservation_item = reservation.reservation_items.new(create_reservation_item_params)

        if reservation_item.save
          render json:{status: 'SUCCESS', message: 'Added item into reservation', data: reservation_item}, status: :ok
        else
          render json:{status: 'ERROR', message: ' Error in adding item into reservation', data: reservation_item.errors}, status: :unprocessable_entity
        end
      end

      def update
        reservation = Reservation.find(params[:reservation_id])
        reservation_item = reservation.reservation_items.find(params[:id])

        if reservation_item.update_attributes(update_reservation_item_params)
          render json: {status: 'SUCCESS', message: 'Reservation Updated', data: reservation_item}, status: :ok
        else
          render json: {status: 'ERROR', message: 'Reservation not updated', data: reservation_item.errors}, status: :ok
        end
      end

      def destroy
        reservation = Reservation.find(params[:reservation_id])
        reservation_item = reservation.reservation_items.find(params[:id])

        if reservation.destroy
          render json: {status: 'SUCCESS', message: 'Reservation Deleted', data: reservation_item}, status: :ok
        else
          render json: {status: 'Error', message: 'Cannot delete reservation', data: reservation_item.errors}, status: :ok
        end
      end


      def create_reservation_item_params
        params.permit(:requested_item, :quantity_borrowed, :borrowed_at, :returned_at)
      end

      def update_reservation_item_params
        params.permit(:requested_item, :quantity_returned, :borrowed_at, :returned_at)
      end

    end
  end
end

app/controllers/reservation_items_controller.rb
class ReservationItemsController < ApplicationController
  before_action :set_reservation_item, only: [:show, :edit, :update, :destroy]


  # GET /reservation_items
  # GET /reservation_items.json
  def index
    @reservation_items = ReservationItem.all
  end

  # GET /reservation_items/1
  # GET /reservation_items/1.json
  def show
  end

  # GET /reservation_items/new
  def new
    @reservation = Reservation.find(params[:reservation_id])
    @reservation_item = @reservation.reservation_items.new

    @locations = Location.all
  end

  # GET /reservation_items/1/edit
  def edit
  end

  # POST /reservation_items
  # POST /reservation_items.json
  def create
    @reservation = Reservation.find(params[:reservation_id])
    @reservation_item = @reservation.reservation_items.new(reservation_item_params)

    respond_to do |format|
      if @reservation_item.save
        format.html { redirect_to reservation_path(@reservation.id), notice: 'Reservation item was successfully created.' }
        format.json { render :show, status: :created, location: @reservation_item }
      else
        format.html { render :new }
        format.json { render json: @reservation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservation_items/1
  # PATCH/PUT /reservation_items/1.json
  def update
    respond_to do |format|

      if @reservation_item.update(reservation_item_params)

        if ReservationItem.compareReturnQtyToBorrowedQty == true
          format.html { redirect_to reservation_path(@reservation.id), notice: 'Reservation item was successfully updated.' }
          format.json { render :show, status: :ok, location: @reservation_item }

        else
          flash[:notice] = "Cannot return more than what was borrowed"
          render :edit
        end

      else

        format.html { render :edit }
        format.json { render json: @reservation_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservation_items/1
  # DELETE /reservation_items/1.json
  def destroy
    @reservation_item.destroy
    respond_to do |format|
      format.html { redirect_to reservation_items_url, notice: 'Reservation item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation_item
      @reservation = Reservation.find(params[:reservation_id])
      @reservation_item = @reservation.reservation_items.find(params[:id])
      #@reservation_item = ReservationItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_item_params
      params.require(:reservation_item).permit(:requested_item, :quantity_borrowed, :quantity_returned, :borrowed_at, :returned_at, :datetime)
    end
end

app/helpers/reservation_items_helper.rb
module ReservationItemsHelper
end

app/views/reservation_items/_form.html.erb
<%= form_with(model: @reservation_item, url: [@reservation, @reservation_item]) do |form| %>
  <% if reservation_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation_item.errors.count, "error") %> prohibited this reservation_item from being saved:</h2>

      <ul>
      <% reservation_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :requested_item %>
    <%= form.text_field :requested_item, id: :reservation_item_requested_item, :readonly => true %>
  </div>


  <div class="field">
    <%= form.label :quantity_borrowed %>
    <%= form.number_field :quantity_borrowed, id: :reservation_item_quantity_borrowed, :readonly=>true %>
  </div>


  <div class="field">
    <%= form.label :quantity_returned, "Total quantity returned" %>
    <%= form.number_field :quantity_returned, id: :reservation_item_quantity_returned %>
  </div>

  <!--
  <div class="field">
    <%= form.label :borrowed_at %>
    <%= form.datetime_select :borrowed_at, id: :reservation_item_borrowed_at %>
  </div>
-->

  <div class="field">
    <%= form.label :returned_at, "Return Date" %>
    <%= form.datetime_select :returned_at, id: :reservation_item_returned_at %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservation_items/_formnew.html.erb
<%= form_with(model: @reservation_item, url: [@reservation, @reservation_item]) do |form| %>
  <% if reservation_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation_item.errors.count, "error") %> prohibited this reservation_item from being saved:</h2>

      <ul>
      <% reservation_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Sort items according to locations -->

  <!-- Returns item id -->
  <div class="field">
    <%= form.label :requested_item, "Item" %>
    <%= form.grouped_collection_select :requested_item, Location.order(:name),:items, :name, :id, :name, include_blank: true %>
  </div>


  <div class="field">
    <%= form.label :quantity_borrowed, "Quantity" %>
    <%= form.number_field :quantity_borrowed, id: :reservation_item_quantity_borrowed %>
  </div>

  <div class="field">
    <%= form.label :borrowed_at, "Start Loan" %>
    <%= form.datetime_select :borrowed_at, id: :reservation_item_borrowed_at %>
  </div>

  <div class="field">
    <%= form.label :returned_at, "End Loan" %>
    <%= form.datetime_select :returned_at, id: :reservation_item_returned_at %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservation_items/edit.html.erb
<h1>Editing Reservation Item</h1>

<%= render 'form', reservation_item: @reservation_item %>

<%= link_to 'Back', reservation_path(@reservation.id) %>

app/views/reservation_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservation Items</h1>

<table>
  <thead>
    <tr>
      <th>Requested item</th>
      <th>Quantity borrowed</th>
      <th>Quantity returned</th>
      <th>Borrowed at</th>
      <th>Returned at</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservation_items.each do |reservation_item| %>
      <tr>
        <td><%= reservation_item.requested_item %></td>
        <td><%= reservation_item.quantity_borrowed %></td>
        <td><%= reservation_item.quantity_returned %></td>
        <td><%= reservation_item.borrowed_at %></td>
        <td><%= reservation_item.returned_at %></td>
        <td><%= reservation_item.datetime %></td>
        <td><%= link_to 'Show', reservation_item %></td>
        <td><%= link_to 'Edit', edit_reservation_item_path(reservation_item) %></td>
        <td><%= link_to 'Destroy', reservation_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation Item', new_reservation_item_path %>

app/views/reservation_items/new.html.erb
<h1>New Reservation Item</h1>

<%= render 'formnew', reservation_item: @reservation_item %>

<%= link_to 'Back', reservation_path(@reservation.id) %>

app/views/reservation_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requested item:</strong>
  <%= @reservation_item.requested_item %>
</p>

<p>
  <strong>Quantity borrowed:</strong>
  <%= @reservation_item.quantity_borrowed %>
</p>

<p>
  <strong>Quantity returned:</strong>
  <%= @reservation_item.quantity_returned %>
</p>

<p>
  <strong>Borrowed at:</strong>
  <%= @reservation_item.borrowed_at %>
</p>

<p>
  <strong>Returned at:</strong>
  <%= @reservation_item.returned_at %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @reservation_item.datetime %>
</p>

<%= link_to 'Edit', edit_reservation_item_path(@reservation_item) %> |
<%= link_to 'Back', reservation_items_path %>