config/routes.rb
Rails.application.routes.draw do


  #devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do

      resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :reservation_items, only: [:new, :create, :edit, :update, :destroy]
      end

    end # v1
  end # api

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reservation_items, only: [:new, :create, :edit, :update]
  end

  root to: "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  has_many :reservation_items

  before_destroy :transferItemsToStoreroom


  def transferItemsToStoreroom

    reservation_items = Reservation.reservation_items.find(params[:id])

    reservation_items.each do |ri|
      
    end
  end
end

app/controllers/api/v1/reservations_controller.rb
module Api
  module V1
    class ReservationsController < ApplicationController

      protect_from_forgery with: :null_session

      #CRUD
      def index
        reservations = Reservation.all
        render json: {status: 'SUCCESS', message: 'Loaded', data: reservations}, status: :ok
      end

      def show

        reservation_items = Reservation.find(params[:id]).reservation_items
        render json:{status: 'SUCCESS', message: 'Showed Reservation Items', data: reservation_items}, status: :unprocessable_entity
      end

      def create
        reservation = Reservation.new(create_reservation_params)

        if reservation.save
          render json:{status: 'SUCCESS', message: 'Reservation Created', data: reservation}, status: :ok
        else
          render json:{status: 'ERROR', message: 'Reservation not created', data: reservation.errors}, status: :unprocessable_entity
        end
      end

      def update

        reservation = Reservation.find(params[:id])

        if reservation.update_attributes(update_reservation_params)
          render json: {status: 'SUCCESS', message: 'Reservation Updated', data: reservation}, status: :ok
        else
          render json: {status: 'ERROR', message: 'Reservation not updated', data: reservation.errors}, status: :ok
        end
      end

      def destroy
        reservation = Reservation.find(params[:id])

        if reservation.destroy
          render json: {status: 'SUCCESS', message: 'Reservation Deleted', data: reservation}, status: :ok
        else
          render json: {status: 'Error', message: 'Cannot delete reservation', data: reservation.errors}, status: :ok
        end
      end

      def create_reservation_params
        params.permit(:name)
      end

      def update_reservation_params
        params.permit(:name, :completed_flag)
      end

    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])
    @reservation_items = @reservation.reservation_items
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_path(), notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:name, :completed_flag)
    end

    def reservation_params
      params.require(:reservation).permit(:name, :completed_flag)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reservation_name %>
  </div>

  <div class="field">
    <%= form.label :completed_flag %>
    <%= form.check_box :completed_flag, id: :reservation_completed_flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_form_new.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reservation_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<h1> Inventory </h1>
<p> Click <%= link_to 'here', locations_path %> to view available inventories </p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.completed_flag %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form_new', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Completed flag:</strong>
  <%= @reservation.completed_flag %>
</p>

</br>


<div>
  <%= link_to 'Add Item to Reservation', new_reservation_reservation_item_path(@reservation.id) %>
</div>
</br></br>

<table>
  <tr>
    <th>Requested</th>
    <th>Qty_Borrowed</th>
    <th>Qty_Returned</th>
    <th>Start_Loan</th>
    <th>End_Loan</th>
    <th>Returned Flag</th>
  </tr>

  <% @reservation_items.each do |r_item|%>
    <tr>
      <td><%=r_item.requested_item%></td>
      <td><%=r_item.quantity_borrowed%></td>
      <td><%=r_item.quantity_returned%></td>
      <td><%=r_item.borrowed_at%></td>
      <td><%=r_item.returned_at%></td>
      <td><%=r_item.returned_flag%></td>
      <td><%= link_to 'edit', edit_reservation_reservation_item_path(@reservation.id, r_item.id)%></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>