config/routes.rb
Rails.application.routes.draw do


  #devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do

      resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :reservation_items, only: [:new, :create, :edit, :update, :destroy]
      end

    end # v1
  end # api

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reservation_items, only: [:new, :create, :edit, :update]
  end

  root to: "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :location

  #validates :name, :uniqueness => {:message => "Title already exists."}
  before_validation :save_item, :on => :create

  private
  def save_item
    if Item.exists?(name: self.name, location_id: self.location_id)
      errors.add(:name, 'Cannot add item, item exists')
    end
  end
end

app/controllers/api/v1/items_controller.rb
module Api
  module V1
    class ItemsController < ApplicationController
      protect_from_forgery with: :null_session


      def create

        item = Item.new(item_params)

        if item.save
          render json:{status: "SUCCESS", message: "Saved Item", data: item}, status: :ok
        else
          render json:{status: "ERROR", message: "Item not saved", data: item.errors}, status: :unprocessable_entity
        end
      end


      def update
        location = Location.find(params[:location_id])
        item = location.items.find(params[:id])

        if item.update_attributes(update_item_params)
          render json:{status: "SUCCESS", message: "Item updated", data: item}, status: :ok
        else
          render json:{status: "ERROR", message: "Item not updated", data: item.errors}, status: :unprocessable_entity
        end
      end

      def destroy
        location = Location.find(params[:location_id])
        item = location.items.find(params[:id])

        if item.destroy
          render json:{status: "SUCCESS", message: "Item destroyed", data: item}, status: :ok
        else
          render json:{status: "ERROR", message: "Item cannot be destroyed", data: item.errors}, status: :unprocessable_entity
        end
      end


      def item_params
        params.permit(:name, :quantity, :location_id)
      end

      def update_item_params
        params.permit(:name, :quantity)
      end


    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [ :show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @location = Location.find(params[:location_id])
    @item = @location.items.new

  end

  # GET /items/1/edit
  def edit

  end

  # POST /items
  # POST /items.json
  def create
    @location = Location.find(params[:location_id])
    @item = @location.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to location_path(@location.id), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else

        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to location_path(@location.id), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    #@location = Location.find(params[:location_id])
    #@item = @location.items.find(params[:id])

    @item.destroy
    respond_to do |format|
      format.html { redirect_to location_path(@location.id), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @location = Location.find(params[:location_id])
      @item = @location.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<!-- Form with can support nested routes -->
<%= form_with(model: item, url: [@location, @item],local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :item_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', location_path(params[:location_id]) %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', location_path(params[:location_id])%>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>