config/routes.rb
Rails.application.routes.draw do


  #devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do

      resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :items, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :reservations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :reservation_items, only: [:new, :create, :edit, :update, :destroy]
      end

    end # v1
  end # api

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:index, :show, :new, :create, :edit, :update] do
        resources :reservation_items, only: [:new, :create, :edit, :update]
  end

  root to: "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/location.rb
class Location < ApplicationRecord
  #has_many :location_items
  #has_many :items, through: :location_items
  has_many :items

  before_validation :save_location, :on => :create

  # Before destroying a location, transfer all items into storeroom

  private
  def save_location
    if Location.exists?(name: self.name)
      errors.add(:base, 'Cannot add location, location exists')

      #return false
    end
  end

end

app/controllers/api/v1/locations_controller.rb
module Api
  module V1
    class LocationsController < ApplicationController
      protect_from_forgery with: :null_session

      def index
        locations = Location.all
        render json: {status: 'SUCCESS', message: 'Loaded Locations', data: locations}, status: :ok
      end

      def show
        location = Location.find(params[:id])
        items = location.items

        render json: {status: 'SUCCESS', message: 'Loaded Locations Items', data: items}, status: :ok
      end

      def create
        location = Location.new(location_params)

        if location.save
          render json: {status: 'SUCCESS', message: 'Saved Location', data: location}, status: :ok
        else
          render json: {status: 'ERROR', message: 'Location not saved', data: location.errors}, status: :unprocessable_entity
        end
      end

      def update
        location = Location.find(params[:id])

        if location.update_attributes(location_params)
          render json: {status: 'SUCCESS', message: 'Location Updated', data: location}, status: :ok
        else
          render json: {status: 'Error', message: 'Location not updated', data: location.errors}, status: :ok
        end
      end

      def destroy
        location = Location.find(params[:id])

        if location.destroy
          render json: {status: 'SUCCESS', message: 'Location Deleted', data: location}, status: :ok
        else
          render json: {status: 'Error', message: 'Cannot delete location', data: location.errors}, status: :ok
        end
      end

      def location_params
        params.permit(:name)
      end
    end

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @items = @location.items
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_path, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_path, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    #@location = Location.find(params[:id])
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_path, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
  <%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1> </br>
<%= link_to 'Add New Location', new_location_path %>

<table>
  <thead>
    <tr>
      <th align="center">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</br><h1>Reservations</h1></br>
<p> Click <%= link_to 'here', reservations_path %> to view your reservations </p>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%=@location.name%> Overview</h1>

<%= link_to 'Add Item to this location', new_location_item_path(params[:id]) %>
</br></br>

<!-- Date Picker to view inventory for a certain date -->


<table>
  <tr>
    <th align="left">Item</th>
    <th>Available</th>
  </tr>

  <% @items.each do |item| %>
  <tr>
    <td align="left"><%=item.name%></td>
    <td align= "center"><%=item.quantity%></td>
    <td><%= link_to 'edit', edit_location_item_path(@location.id, item.id) %></td>
    <td><%= link_to 'destroy',location_item_path(@location.id, item.id), method: :delete %></td>
  </tr>

  <%end%>
</table>

<%= link_to 'Back', locations_path %>